term.clear()
term.setCursorPos(1, 1)
print(" /\\  AMERICAN")
print("/\\/\\ MEGATRIFORCE           AMIBIOS (C)1992")
print()
print("Intel Pentium II - 233MHz")
print("Checking RAM")
sleep(0.5)
print("256KB OK")
sleep(2)

term.clear()
term.setCursorPos(1, 1)
print("Searching for HDD... OK")
sleep(0.5)
print("Searching for bootable OS... OK")
sleep(0.5)
print("Booting...")
sleep(2)

term.clear()
term.setCursorPos(1, 1)
print("TrollDOS Version 4.2")
print("Copyright (C) Eduard Khil 1992")
print()
sleep(1)